spring.application.name=PortfolioApi

# MongoDB Configuration
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/portfolio_db}

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Your name shown in emails
app.mail.owner-email=${OWNER_EMAIL:mtapan2004@gmail.com}
app.mail.owner-name=Tapan Manna