spring.application.name=PortfolioApi
# Local MongoDB
#spring.mongodb.uri=mongodb://localhost:27017/portfolio_db
#spring.mongodb.database=portfolio_db

# For MongoDB Atlas (cloud) ? uncomment and replace:
 spring.mongodb.uri=mongodb+srv://root:Tmanna@cluster0.crr0jp6.mongodb.net/portfolio_db?retryWrites=true&w=majority

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tabc1196@gmail.com
spring.mail.password=ixhvmsepzbjzbvoz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Your name shown in emails
app.mail.owner-email=mtapan2004@gmail.com
app.mail.owner-name=Tapan Manna